{
 "title": "blob",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Endpunkte Avg 500er über Anzahl -> gleich 0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "DMS Anzeige",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/dms\"}[30m])) < bool 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESB Anzeige",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/esb\"}[30m])) < bool 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WWS Anzeige",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/wws\"}[30m])) < bool 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DMS Errors Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/dms\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESB Errors Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/esb\"}[30m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WWS Errors Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\", uri=\"/api/error/wws\"}[30m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      },
      {
       "id": "75b7d197",
       "operator": "=",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "500" ],
       "valueType": "int"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Eigene Up Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Nagios Anzeige über Querry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(up == 1) == 6) - 5 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beispiel SP Services Ansicht",
   "type": "stat",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}