global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['A:8080']

  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['B:8081']

  - job_name: 'middleware'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['C:8082']
  - job_name: 'DMS'
    metrics_path: '/api/status/dms'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'A:8080' ]
  - job_name: 'WWS'
    metrics_path: '/api/status/wws'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'A:8080' ]
  - job_name: 'ESB'
    metrics_path: '/api/status/esb'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'A:8080' ]